"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import AppShell from "@/components/AppShell";
import Header from "@/components/Header";
import {api} from "@/lib/api";

type Row=Record<string,unknown>;
type Group={records:Row[]};
type Capital={buying_power:number;planned_reservations:number;deployable_cash:number;broker_hold_created:boolean};
type Portfolio={trading:string;capital:Capital;snapshot:null|{status:string;stale:boolean;observed_at:string;summary:{portfolio_value:number|null;buying_power:number|null;cash:number|null;holding_count:number;order_count:number;fill_count:number};holdings:Group[];reconciliation:{status:string;dataset_failures:unknown[]}}};
type Risk={controls:{kill_switch_engaged:boolean;circuit_breaker_engaged:boolean};assessment_counts:Record<string,number>};
type Intel={id:number;artifact_type:string;subject:string;thesis:string;recommendation:string;confidence:number;governance:string;governance_reason:string;created_at:string};
type DataStatus={record_count:number;quality_issue_count:number;freshest:Record<string,string>};
type News={id:number;symbol:string|null;event_time:string;source_url:string;payload:{url?:string;title?:string;summary?:string;source?:string;overall_sentiment_label?:string;ticker_sentiment?:{ticker:string;relevance_score:string;ticker_sentiment_label:string}[]}};
type CorporateAction={id:number;symbol:string|null;event_time:string;payload:{action?:string;amount?:number|string;ex_dividend_date?:string;payment_date?:string}};
type History={snapshot_count:number;change_pct:number|null;direction:string};
type Intent={id:number;symbol:string;side:string;quantity:number;limit_price:number;status:string;expires_at:string;human_approval_required:boolean};
type Readiness={paper_trial_ready:boolean;live_ready:boolean;gates:Record<string,boolean>;trading:string};
type Plan={id:number;symbol:string;side:string;quantity:number;reference_price:number;reserved_notional:number;planned_entry_date:string;status:string;rationale:string;revalidation_detail:string;notification_status:string};
type Plans={plans:Plan[];planning_sessions:string[];capacity:Capital;trading:string};
const money=(v:number|null|undefined)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v);
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;
const text=(value:unknown)=>value==null?"":String(value);
function nestedRows(value:unknown):Row[]{if(Array.isArray(value))return value.flatMap(nestedRows);if(!value||typeof value!=="object")return[];const row=value as Row;for(const key of ["positions","results","items","data"]){if(row[key]!=null){const found=nestedRows(row[key]);if(found.length)return found}}return Object.keys(row).some(k=>["symbol","instrument","asset_code"].includes(k))?[row]:[]}
function symbolOf(row:Row){return text(row.symbol||row.instrument||row.asset_code).toUpperCase()}
function articleUrl(news:News){try{const value=new URL(news.payload.url||news.source_url);return value.protocol==="https:"?value.toString():"#"}catch{return "#"}}
export default function Dashboard(){
 const[portfolio,setPortfolio]=useState<Portfolio|null>(null),[risk,setRisk]=useState<Risk|null>(null),[intel,setIntel]=useState<Intel[]>([]),[data,setData]=useState<DataStatus|null>(null),[news,setNews]=useState<News[]>([]),[actions,setActions]=useState<CorporateAction[]>([]),[history,setHistory]=useState<History|null>(null),[intents,setIntents]=useState<Intent[]>([]),[readiness,setReadiness]=useState<Readiness|null>(null),[plans,setPlans]=useState<Plans|null>(null),[error,setError]=useState("");
 useEffect(()=>{Promise.all([api<Portfolio>("/api/portfolio"),api<Risk>("/api/risk/status"),api<Intel[]>("/api/intelligence/artifacts?limit=20"),api<DataStatus>("/api/data/status"),api<News[]>("/api/data/records?data_type=NEWS&limit=100"),api<CorporateAction[]>("/api/data/records?data_type=CORPORATE_ACTION&limit=250"),api<History>("/api/portfolio/history?limit=100"),api<Intent[]>("/api/controlled-live/intents?limit=20"),api<Readiness>("/api/controlled-live/readiness"),api<Plans>("/api/planned-trades")]).then(([p,r,i,d,n,a,h,t,ready,planned])=>{setPortfolio(p);setRisk(r);setIntel(i);setData(d);setNews(n);setActions(a);setHistory(h);setIntents(t);setReadiness(ready);setPlans(planned)}).catch(e=>setError(e.message))},[]);
 const s=portfolio?.snapshot;
 const positions=useMemo(()=>s?.holdings.flatMap(g=>g.records.flatMap(nestedRows))??[],[s]);
 const symbols=useMemo(()=>new Set(positions.map(symbolOf).filter(Boolean)),[positions]);
 const relevantNews=useMemo(()=>{const portfolioNews=news.filter(n=>n.symbol&&symbols.has(n.symbol));return(portfolioNews.length?portfolioNews:news).slice(0,5)},[news,symbols]);
 const upcoming=useMemo(()=>actions.filter(a=>a.payload.action==="DIVIDEND"&&new Date(a.payload.ex_dividend_date||a.event_time)>new Date()).sort((a,b)=>new Date(a.payload.ex_dividend_date||a.event_time).getTime()-new Date(b.payload.ex_dividend_date||b.event_time).getTime()).slice(0,4),[actions]);
 const governed=intel.filter(x=>x.governance!=="REJECTED"),activeIntents=intents.filter(x=>["PROPOSED","APPROVED_TRIAL_ONLY","REVIEWED_TRIAL_ONLY"].includes(x.status));
 const tenDayPlans=(plans?.plans??[]).filter(x=>["PLANNED","REVALIDATION_BLOCKED","READY_FOR_FINAL_APPROVAL"].includes(x.status)&&plans?.planning_sessions.includes(x.planned_entry_date)).sort((a,b)=>a.planned_entry_date.localeCompare(b.planned_entry_date));
 const stopped=!!(risk?.controls.kill_switch_engaged||risk?.controls.circuit_breaker_engaged),needsApproval=activeIntents.some(x=>x.human_approval_required)||governed.some(x=>x.governance==="HUMAN_REVIEW"),attention=(s?.stale?1:0)+(s?.reconciliation.dataset_failures.length??0)+(data?.quality_issue_count??0);
 const posture=stopped?"RISK STOP":needsApproval?"APPROVAL REQUIRED":attention?"DATA ATTENTION":governed.length?"DECISION READY":"NO ACTION";
 const invested=s?.summary.portfolio_value!=null&&s.summary.cash!=null?Math.max(0,s.summary.portfolio_value-s.summary.cash):null;
 async function cancelPlan(id:number){const reason=prompt("Reason for cancelling this planned trade (10+ characters)");if(!reason)return;try{const me=await api<{csrf_token:string}>("/api/auth/me");await api(`/api/planned-trades/${id}/cancel`,{method:"POST",headers:{"X-CSRF-Token":me.csrf_token},body:JSON.stringify({reason})});setPlans(await api<Plans>("/api/planned-trades"));setPortfolio(await api<Portfolio>("/api/portfolio"))}catch(e){setError((e as Error).message)}}
 return <AppShell><Header title="Investment Command Center" subtitle="Capital, opportunities, governed decisions, portfolio news, and approval readiness."/>
 <div className="dashboard-notice"><span>{posture}</span>{stopped?"Deterministic controls prevent authorization.":needsApproval?"A governed investment action requires your review.":"No verified action currently requires approval."} Trading remains disabled.</div>
 {error&&<div className="guardrail">Decision evidence unavailable: {error}</div>}
 <div className="grid">
  <div className="card metric"><label>Portfolio value</label><strong>{money(s?.summary.portfolio_value)}</strong><span className="sub">{s?`${s.status} · ${s.stale?"STALE":"FRESH"}`:"Awaiting broker snapshot"}</span></div>
  <div className="card metric"><label>Deployable cash</label><strong>{money(plans?.capacity.deployable_cash??portfolio?.capital?.deployable_cash)}</strong><span className="sub">Buying power {money(s?.summary.buying_power)} · planned {money(plans?.capacity.planned_reservations??portfolio?.capital?.planned_reservations)}</span></div>
  <div className="card metric"><label>Capital deployed</label><strong>{money(invested)}</strong><span className="sub">{s?.summary.holding_count??0} verified positions</span></div>
  <div className="card metric"><label>Verified direction</label><strong className={(history?.change_pct??0)>0?"healthy":(history?.change_pct??0)<0?"bad":""}>{pct(history?.change_pct)}</strong><span className="sub">{history?.snapshot_count??0} broker snapshots · {history?.direction??"BASELINE"}</span></div>
  <section className="card span8"><div className="panel-heading"><div><div className="card-title">Decision and approval queue</div><p className="sub">Only current investment proposals and immutable order intents appear here.</p></div><Link className="data-badge" href="/trial">OPEN APPROVAL WORKSPACE</Link></div>
{plans?.plans.filter(x=>["PLANNED","REVALIDATION_BLOCKED","READY_FOR_FINAL_APPROVAL"].includes(x.status)).map(x=><div className="decision-row" key={`plan-${x.id}`}><div><strong>PLANNED BUY · {x.symbol} · {money(x.reserved_notional)} reserved</strong><span>{x.quantity} shares near {money(x.reference_price)} · entry {new Date(`${x.planned_entry_date}T12:00:00`).toLocaleDateString()} · {x.rationale}</span></div><div><strong className={x.status==="READY_FOR_FINAL_APPROVAL"?"healthy":"warn"}>{x.status.replaceAll("_"," ")}</strong><br/><button onClick={()=>cancelPlan(x.id)}>CANCEL & RELEASE</button></div></div>)}
   {activeIntents.map(x=><div className="decision-row" key={`intent-${x.id}`}><div><strong>{x.side} {x.symbol} · {x.quantity} shares</strong><span>Limit {money(x.limit_price)} · expires {new Date(x.expires_at).toLocaleTimeString()}</span></div><strong className="warn">{x.status.replaceAll("_"," ")}</strong></div>)}
   {governed.slice(0,4).map(x=><div className="decision-row" key={`intel-${x.id}`}><div><strong>{x.recommendation} · {x.subject}</strong><span>{x.thesis} · confidence {(x.confidence*100).toFixed(0)}%</span></div><strong className={x.governance==="ELIGIBLE_FOR_RISK_REVIEW"?"healthy":"warn"}>{x.governance.replaceAll("_"," ")}</strong></div>)}
   {!(plans?.plans.some(x=>["PLANNED","REVALIDATION_BLOCKED","READY_FOR_FINAL_APPROVAL"].includes(x.status)))&&!activeIntents.length&&!governed.length&&<div className="decision-empty">No actionable proposal or approval request. Aegis will not invent one.</div>}
  </section>
  <section className="card span4"><div className="card-title">Decision guardrails</div><div className="status-row"><span>Risk controls<br/><small>Kill switch and circuit breaker</small></span><strong className={stopped?"bad":"healthy"}>{stopped?"STOPPED":"CLEAR"}</strong></div><div className="status-row"><span>Broker evidence<br/><small>Age of latest account snapshot</small></span><strong className={!s||s.stale?"warn":"healthy"}>{!s?"MISSING":s.stale?"STALE":"FRESH"}</strong></div><div className="status-row"><span>Paper trial<br/><small>Simulation readiness gates</small></span><strong className={readiness?.paper_trial_ready?"healthy":"warn"}>{readiness?.paper_trial_ready?"READY":"BLOCKED"}</strong></div><div className="status-row"><span>Live authorization<br/><small>All live-trading gates</small></span><strong className="bad">{readiness?.live_ready?"READY":"BLOCKED"}</strong></div><Link className="sub" href="/risk">Inspect deterministic controls →</Link></section>
  <section className="card span8"><div className="panel-heading"><div><div className="card-title">Portfolio and monitored-universe news</div><p className="sub">{symbols.size?`Prioritized for ${[...symbols].join(", ")}`:"No holdings; showing the latest monitored-universe intelligence."}</p></div><Link className="data-badge" href="/intelligence">ANALYZE EVIDENCE</Link></div>{relevantNews.length?relevantNews.map(n=><a className="news-row" key={n.id} href={articleUrl(n)} target="_blank" rel="noreferrer"><div><strong>{n.symbol??"MARKET"} · {n.payload.title??"Untitled market report"}</strong><span>{n.payload.source??"External source"} · {new Date(n.event_time).toLocaleString()}</span></div><span className="pill">{n.payload.overall_sentiment_label??"UNRATED"}</span></a>):<div className="decision-empty">No fresh portfolio or monitored-universe news is available.</div>}</section>
  <section className="card span4"><div className="card-title">10-day capital plan</div>{tenDayPlans.length?tenDayPlans.map(x=><div className="status-row" key={x.id}><span><strong>{x.side} {x.symbol}</strong><br/><small>{new Date(`${x.planned_entry_date}T12:00:00`).toLocaleDateString()} · revalidates before action</small></span><strong>{money(x.reserved_notional)}</strong></div>):<div className="decision-empty">No capital-reserved buys are planned. Research candidates are not presented as commitments.</div>}<Link className="sub" href="/dividends">Open 10-session opportunity calendar →</Link></section>
  <section className="card span12"><div className="panel-heading"><div><div className="card-title">Evidence readiness</div><p className="sub">Investment-data coverage only; infrastructure detail remains under System.</p></div><Link className="data-badge" href="/data">OPEN DATA COVERAGE</Link></div><div className="evidence-strip"><div><span>Normalized records</span><strong>{data?.record_count.toLocaleString()??"—"}</strong></div><div><span>Quality issues</span><strong className={data?.quality_issue_count?"warn":"healthy"}>{data?.quality_issue_count??"—"}</strong></div><div><span>Latest quote evidence</span><strong>{data?.freshest?.BROKER_QUOTE?new Date(data.freshest.BROKER_QUOTE).toLocaleDateString():"—"}</strong></div><Link className="evidence-link" href="/dividends"><span>Upcoming candidates</span><strong>{upcoming.length}</strong><small>OPEN CALENDAR →</small></Link></div></section>
 </div></AppShell>
}
