"""Add Phase 5 reproducible Aegis Lab artifacts."""
from alembic import op
import sqlalchemy as sa
revision="0008_phase5_aegis_lab";down_revision="0007_phase4_strategy_engine";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("lab_runs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("strategy_version_id",sa.Integer(),sa.ForeignKey("strategy_versions.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("configuration",sa.JSON(),nullable=False),sa.Column("configuration_checksum",sa.String(64),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("equity_curve",sa.JSON(),nullable=False),sa.Column("walk_forward",sa.JSON(),nullable=False),sa.Column("monte_carlo",sa.JSON(),nullable=False),sa.Column("sensitivity",sa.JSON(),nullable=False),sa.Column("data_provenance",sa.JSON(),nullable=False),sa.Column("detail",sa.Text(),nullable=False,server_default=""),sa.Column("created_by",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("strategy_version_id","configuration_checksum",name="uq_lab_run_reproducible"))
 for c in ("strategy_version_id","status","configuration_checksum","created_at"):op.create_index(f"ix_lab_runs_{c}","lab_runs",[c])
 op.create_table("lab_trades",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("run_id",sa.Integer(),sa.ForeignKey("lab_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("symbol",sa.String(32),nullable=False),sa.Column("entry_day",sa.Date(),nullable=False),sa.Column("exit_day",sa.Date(),nullable=False),sa.Column("shares",sa.Float(),nullable=False),sa.Column("entry_price",sa.Float(),nullable=False),sa.Column("exit_price",sa.Float(),nullable=False),sa.Column("dividends",sa.Float(),nullable=False),sa.Column("costs",sa.Float(),nullable=False),sa.Column("pnl",sa.Float(),nullable=False),sa.Column("return_pct",sa.Float(),nullable=False),sa.Column("holding_days",sa.Integer(),nullable=False),sa.Column("exit_reason",sa.String(32),nullable=False),sa.Column("max_drawdown_pct",sa.Float(),nullable=False))
 for c in ("run_id","symbol","entry_day","exit_day"):op.create_index(f"ix_lab_trades_{c}","lab_trades",[c])
def downgrade():op.drop_table("lab_trades");op.drop_table("lab_runs")
