"""Add Phase 6 deterministic risk authorization artifacts."""
from alembic import op
import sqlalchemy as sa
revision="0009_phase6_aegis_risk";down_revision="0008_phase5_aegis_lab";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("risk_policies",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("version",sa.Integer(),nullable=False,unique=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("configuration",sa.JSON(),nullable=False),sa.Column("checksum",sa.String(64),nullable=False,unique=True),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_by",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
 op.create_index("ix_risk_policies_version","risk_policies",["version"]);op.create_index("ix_risk_policies_checksum","risk_policies",["checksum"]);op.create_index("ix_risk_policies_active","risk_policies",["active"])
 op.create_table("risk_control_state",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("kill_switch_engaged",sa.Boolean(),nullable=False),sa.Column("circuit_breaker_engaged",sa.Boolean(),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("updated_by",sa.String(64),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
 op.create_table("risk_assessments",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("policy_id",sa.Integer(),sa.ForeignKey("risk_policies.id",ondelete="RESTRICT"),nullable=False),sa.Column("proposal_id",sa.String(64),nullable=False),sa.Column("strategy_decision_id",sa.Integer(),sa.ForeignKey("strategy_decisions.id",ondelete="RESTRICT"),nullable=True),sa.Column("request_checksum",sa.String(64),nullable=False,unique=True),sa.Column("request_snapshot",sa.JSON(),nullable=False),sa.Column("outcome",sa.String(20),nullable=False),sa.Column("reason_codes",sa.JSON(),nullable=False),sa.Column("checks",sa.JSON(),nullable=False),sa.Column("notional",sa.Float(),nullable=False),sa.Column("risk_authorized",sa.Boolean(),nullable=False),sa.Column("created_by",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
 for c in ("policy_id","proposal_id","strategy_decision_id","request_checksum","outcome","risk_authorized","created_at"):op.create_index(f"ix_risk_assessments_{c}","risk_assessments",[c])
def downgrade():op.drop_table("risk_assessments");op.drop_table("risk_control_state");op.drop_table("risk_policies")
