"""phase8 isolated paper simulator"""
from alembic import op
import sqlalchemy as sa
revision="0011_phase8_simulator";down_revision="0010_phase7_intelligence";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("paper_accounts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(80),nullable=False,unique=True),sa.Column("initial_cash",sa.Float(),nullable=False),sa.Column("cash",sa.Float(),nullable=False),sa.Column("realized_pnl",sa.Float(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("paper_orders",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("account_id",sa.Integer(),sa.ForeignKey("paper_accounts.id",ondelete="RESTRICT"),nullable=False),sa.Column("risk_assessment_id",sa.Integer(),sa.ForeignKey("risk_assessments.id",ondelete="RESTRICT"),nullable=False,unique=True),sa.Column("quote_record_id",sa.Integer(),sa.ForeignKey("data_records.id",ondelete="RESTRICT"),nullable=False),sa.Column("symbol",sa.String(32),nullable=False),sa.Column("side",sa.String(4),nullable=False),sa.Column("quantity",sa.Float(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("created_by",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("paper_fills",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("order_id",sa.Integer(),sa.ForeignKey("paper_orders.id",ondelete="RESTRICT"),nullable=False,unique=True),sa.Column("price",sa.Float(),nullable=False),sa.Column("quantity",sa.Float(),nullable=False),sa.Column("commission",sa.Float(),nullable=False),sa.Column("slippage_bps",sa.Float(),nullable=False),sa.Column("filled_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("paper_positions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("account_id",sa.Integer(),sa.ForeignKey("paper_accounts.id",ondelete="CASCADE"),nullable=False),sa.Column("symbol",sa.String(32),nullable=False),sa.Column("quantity",sa.Float(),nullable=False),sa.Column("average_cost",sa.Float(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("account_id","symbol",name="uq_paper_position_account_symbol"))
def downgrade():op.drop_table("paper_positions");op.drop_table("paper_fills");op.drop_table("paper_orders");op.drop_table("paper_accounts")
