PHASES = [
    (1, "AEGIS CORE / FOUNDATION", "A reproducible, secure development platform", [
        "Create private GitHub repository architecture", "Establish main, develop, and feature/* workflow", "Prepare Ubuntu development environment", "Install/configure Git, GitHub CLI, Docker, Docker Compose, Python, Node.js and required build tools", "Configure Codex development workflow", "Create permanent repository structure", "Create AGENTS.md", "Create docs/architecture.md", "Create docs/roadmap.md", "Create docs/development-status.md", "Create docs/security-model.md", "Create docs/data-model.md", "Create docs/decisions/", "Document all permanent architecture rules", "Create Docker development environment", "Create FastAPI backend", "Create PostgreSQL database", "Create Redis service", "Create Next.js/React frontend", "Make Docker Compose capable of starting the development stack", "Build GET /health endpoint", "Build GET /api/status endpoint", "Validate PostgreSQL connectivity", "Validate Redis connectivity", "Implement structured logging", "Implement configuration management", "Build Aegis Alpha frontend shell", "Build dashboard", "Build system status panel", "Connect frontend to FastAPI", "Configure SQLAlchemy", "Configure Alembic migrations", "Create initial application/system tables", "Create .env.example", "Ensure real secrets are excluded from Git", "Configure secure SSH guidance", "Configure Ubuntu UFW firewall", "Establish development credentials", "Document staging/production secret handling", "Establish pytest backend tests", "Establish API integration tests", "Establish frontend tests", "Establish Docker startup/health tests", "Create GitHub CI design/workflow", "Run backend tests in CI", "Run frontend checks in CI", "Validate builds in CI", "Prevent broken code merging to main where practical", "Establish ChatGPT/Codex continuity through repository documentation", "Require development-status.md updates after meaningful work", "Define local environment", "Define staging environment", "Define production environment", "Prepare DigitalOcean deployment architecture", "Document Ubuntu Droplet design", "Document networking plan", "Document domain/DNS plan", "Document reverse proxy plan", "Document backup plan", "Document deployment workflow", "Establish Robinhood connectivity as a future integration validation milestone", "Document dedicated Robinhood Agentic account requirement", "Document Robinhood Trading MCP integration plan", "Create future RobinhoodBrokerAdapter interface/placeholder only", "Create future GET /api/broker/status interface/placeholder", "Dashboard must have future Robinhood Connected/Disconnected/Error status location", "Trading must remain DISABLED", "Create Phase 1 completion criteria", "Create release/tag plan for v0.1.0-core"
    ]),
    (2, "AEGIS CONSOLE", "Operator experience", ["User authentication improvements", "Dashboard", "Main navigation", "Portfolio views", "Strategy library", "System settings", "Activity logs", "Responsive desktop/mobile UI"]),
    (3, "AEGIS DATA", "Trusted market and reference data", ["Market-data provider abstraction", "Historical OHLCV ingestion", "Real-time quote ingestion", "Fundamentals", "Corporate actions", "Economic data", "News", "Data normalization", "Caching", "Data-quality validation", "Market calendar and session awareness", "Public-source intelligence provenance, freshness and licensing"]),
    (4, "AEGIS STRATEGY ENGINE", "Deterministic strategy decisions", ["Strategy specification / DSL", "Universe selection", "Indicators", "Entry rules", "Exit rules", "Position sizing", "Strategy schedules", "Filters", "Parameters", "Strategy versioning"]),
    (5, "AEGIS LAB", "Reproducible research and backtesting", ["Historical backtesting", "Transaction costs", "Slippage", "Dividends", "Splits", "Benchmark comparison", "Walk-forward testing", "Monte Carlo testing", "Parameter sensitivity", "Drawdown analysis", "Sharpe ratio", "Sortino ratio", "Exposure analysis", "Trade-level inspection"]),
    (6, "AEGIS RISK", "Deterministic authorization", ["Deterministic risk engine", "Position limits", "Portfolio exposure limits", "Sector limits", "Correlation exposure", "Maximum daily loss", "Maximum drawdown", "Volatility limits", "Buying-power checks", "Order sanity checks", "Duplicate-order prevention", "Stale-data detection", "Circuit breakers", "Global kill switch"]),
    (7, "AEGIS INTELLIGENCE", "AI proposes; it never bypasses RiskEngine", ["AI-assisted strategy creation", "Strategy critique", "Market regime analysis", "News analysis", "Fundamental analysis", "Parameter research", "Post-trade review", "Anomaly detection", "Multi-agent Strategy Council", "Pre-market operator decision briefing", "Post-market performance and highlights digest", "Urgent attention and user-interaction alert classification", "Actionable intelligence with citations, freshness and confidence", "Independent proposal verification, consensus policy and fail-closed human escalation"]),
    (8, "AEGIS SIMULATOR", "Independent paper environment", ["Live market-data simulation", "Paper execution", "Simulated fills", "Simulated portfolio", "Independent paper-trading environment", "Performance tracking"]),
    (9, "AEGIS GATEWAY", "Broker-neutral guarded execution", ["Broker abstraction", "Robinhood Agentic Trading integration", "Robinhood Trading MCP", "Account synchronization", "Balances", "Holdings", "Orders", "Fills", "Order reconciliation", "Failures", "Retries", "Brokerage audit logging", "Execution safeguards", "Verified portfolio snapshots for operator communications"]),
    (10, "AEGIS CONTROLLED LIVE", "Human-approved real-capital validation", ["Real capital", "Human approval required for each proposed order", "Compare intended and actual orders", "Validate fills", "Reconcile portfolio state", "Confirm risk controls"]),
    (11, "AEGIS AUTONOMY", "Granular bounded authorization", ["Strategy-specific trading authorization", "Strategy capital limits", "Asset restrictions", "Position-size limits", "Daily-loss limits", "Portfolio limits", "Granular autonomous permissions"]),
    (12, "AEGIS EVOLUTION", "Continuous governed improvement", ["Continuous strategy research", "Strategy refinement", "Portfolio allocation between strategies", "Regime-dependent strategy selection", "AI agent evaluation", "Alternative datasets", "Additional broker integrations", "Additional asset classes", "Optional local AI inference", "Provider-neutral notification channels", "Scheduled email delivery with retry, deduplication and audit", "Operator notification preferences and escalation policy"]),
]

