"use client";
import {useEffect,useState} from "react";
import AppShell from "../../components/AppShell";
import Header from "../../components/Header";
import {api} from "../../lib/api";
type Event={id:number;symbol:string;company_name:string|null;ex_dividend_date:string;amount:string|null;payment_frequency:string|null;payment_date:string|null;annual_yield_pct:string|null;provider:string;coverage:string;quality_status:string;estimated_recovery_days:number|null;recovery_observations:number;recovery_probability_pct:number|null;recovery_status:string;reference_price:number|null};
type Session={session_date:string;events:Event[]};type Calendar={sessions:Session[];event_count:number;primary_provider:string;enrichment_providers:string[];trading:string};
const money=(value:string|null)=>value==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:3}).format(Number(value));
export default function DividendCalendar(){
 const[data,setData]=useState<Calendar|null>(null),[error,setError]=useState("");
 useEffect(()=>{api<Calendar>("/api/data/dividend-calendar?trading_days=10").then(setData).catch(e=>setError(e.message))},[]);
 return <AppShell><Header title="Dividend Calendar" subtitle="Upcoming ex-dividend events across the next 10 NYSE trading sessions."/><div className="guardrail">Robinhood is primary · Recovery estimates require at least 12 historical dividend events · Research only · Trading disabled</div>{error&&<div className="guardrail">Dividend calendar unavailable: {error}</div>}{!data?<div className="loading">Loading verified dividend schedules…</div>:<><div className="grid"><div className="card metric"><label>Upcoming events</label><strong>{data.event_count}</strong><span className="sub">Next 10 trading days</span></div><div className="card metric"><label>Primary source</label><strong>{data.primary_provider}</strong><span className="sub">Official read-only broker data</span></div><div className="card metric"><label>Enrichment</label><strong>{data.enrichment_providers.length}</strong><span className="sub">Alpha Vantage · Alpaca</span></div><div className="card metric"><label>Trading</label><strong className="bad">{data.trading}</strong><span className="sub">Calendar cannot create orders</span></div></div><div className="dividend-calendar">{data.sessions.map(day=><section className="card dividend-day" key={day.session_date}><div className="calendar-date"><strong>{new Date(`${day.session_date}T12:00:00`).toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</strong><span>{day.events.length} event{day.events.length===1?"":"s"}</span></div>{day.events.length?day.events.map(event=><div className="dividend-event" key={event.id}><div className="dividend-identity"><strong className="ticker-symbol">{event.symbol||"UNKNOWN"}</strong><b>{event.company_name??"Company name unavailable"}</b><span>EX-DIVIDEND · {event.ex_dividend_date}</span><span>{event.payment_frequency??"Frequency unavailable"} · SOURCE {event.provider}</span><span>ANNUAL YIELD · {event.annual_yield_pct==null?"Unavailable":`${Number(event.annual_yield_pct).toFixed(2)}%`}</span><span>EST. RECOVERY · {event.estimated_recovery_days==null?`Insufficient history (${event.recovery_observations}/12 events)`:`${event.estimated_recovery_days} trading days`}</span></div><div className="dividend-amount"><strong>{money(event.amount)}</strong><span>PER SHARE</span></div></div>):<p className="sub">No verified ex-dividend events.</p>}</section>)}</div></>}</AppShell>
}
